name: Build and Release

on:
  push:
    branches:
      - master
    paths:
      - 'src/*'
      - 'Cargo.toml'

jobs:
  windows:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Lint
        run: cargo clippy

      - name: Test
        run: cargo test

      - name: Build
        run: |
          rustup set default-host x86_64-pc-windows-gnu
          rustup toolchain install stable-gnu
          rustup target add x86_64-pc-windows-gnu
          cargo build --target x86_64-pc-windows-gnu
      

      - name: Upload Artifact
        uses: actions/upload-artifact@v6
        with:
          name: windows-latest
          path: build/startup-millenium.exe

  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Lint
        run: cargo clippy

      - name: Test
        run: cargo test

      - name: Build
        run: cargo build --release
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v6
        with:
          name: ubuntu-latest
          path: build/startup-millenium

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [windows, linux]

    steps:
      - uses: actions/checkout@v6

      - name: Download artifacts
        uses: actions/download-artifact@v7

      - name: Release Build
        uses: softprops/action-gh-release@v2
        with:
          name: Release
          tag_name: ${{ github.run_id }}
          body: |
            **This release has been built by Github Actions**
            [Link to build](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})
          files: |
            startup-millenium
            startup-millenium.exe
